from res_flow.resflow import ACT_FNS


def add_res_flow_arguments(parser):
    parser.add_argument('--block', type=str, choices=['resblock', 'coupling'], default='resblock')

    parser.add_argument('--coeff', type=float, default=0.98)
    parser.add_argument('--vnorms', type=str, default='2222')
    parser.add_argument('--n-lipschitz-iters', type=int, default=None)
    parser.add_argument('--sn-tol', type=float, default=1e-3)
    parser.add_argument('--learn-p', type=eval, choices=[True, False], default=False)

    parser.add_argument('--n-power-series', type=int, default=None)
    parser.add_argument('--factor-out', type=eval, choices=[True, False], default=False)
    parser.add_argument('--n-dist', choices=['geometric', 'poisson'], default='poisson')
    parser.add_argument('--n-samples', type=int, default=1)
    parser.add_argument('--n-exact-terms', type=int, default=2)
    parser.add_argument('--var-reduc-lr', type=float, default=0)
    parser.add_argument('--neumann-grad', type=eval, choices=[True, False], default=True)
    parser.add_argument('--mem-eff', type=eval, choices=[True, False], default=True)

    parser.add_argument('--act', type=str, choices=ACT_FNS.keys(), default='swish')
    parser.add_argument('--idim', type=int, default=512)
    parser.add_argument('--nblocks', type=str, default='16-16-16')
    parser.add_argument('--squeeze-first', type=eval, default=False, choices=[True, False])
    parser.add_argument('--actnorm', type=eval, default=True, choices=[True, False])
    parser.add_argument('--fc-actnorm', type=eval, default=False, choices=[True, False])
    parser.add_argument('--batchnorm', type=eval, default=False, choices=[True, False])
    parser.add_argument('--dropout', type=float, default=0.)
    parser.add_argument('--fc', type=eval, default=False, choices=[True, False])
    parser.add_argument('--kernels', type=str, default='3-1-3')
    parser.add_argument('--add-noise', type=eval, choices=[True, False], default=True)
    parser.add_argument('--quadratic', type=eval, choices=[True, False], default=False)
    parser.add_argument('--fc-end', type=eval, choices=[True, False], default=True)
    parser.add_argument('--fc-idim', type=int, default=128)
    parser.add_argument('--preact', type=eval, choices=[True, False], default=True)
    parser.add_argument('--padding', type=int, default=0)
    parser.add_argument('--first-resblock', type=eval, choices=[True, False], default=True)
    parser.add_argument('--cdim', type=int, default=256)

    parser.add_argument('--optimizer', type=str, choices=['adam', 'adamax', 'rmsprop', 'sgd'], default='adam')
    parser.add_argument('--lr', help='Learning rate', type=float, default=1e-3)
    parser.add_argument('--wd', help='Weight decay', type=float, default=0)
    #parser.add_argument('--warmup-iters', type=int, default=1000)
    parser.add_argument('--annealing-iters', type=int, default=0)
    parser.add_argument('--ema-val', type=eval, choices=[True, False], default=True)
    parser.add_argument('--update-freq', type=int, default=1)

    parser.add_argument('--task', type=str, choices=['density', 'classification', 'hybrid'], default='density')
    parser.add_argument('--scale-dim', type=eval, choices=[True, False], default=False)
    parser.add_argument('--rcrop-pad-mode', type=str, choices=['constant', 'reflect'], default='reflect')
    parser.add_argument('--padding-dist', type=str, choices=['uniform', 'gaussian'], default='uniform')
